name: create-release
description: Orchestrate complete product release workflow for FINISHED, PRODUCTION-READY features. Executes comprehensive release preparation including screenshot capture, documentation creation/updates, knowledge base sync, and customer announcement generation.

trigger:
  keywords:
    - "create a release"
    - "create release for"
    - "release materials"
    - "prepare a release"
    - "launch announcement"

inputs:
  - name: feature_name
    description: Name of the feature being released
    required: true
    type: string

  - name: feature_description
    description: Brief description of what was built
    required: false
    type: string

  - name: category
    description: Documentation category (features, integrations, getting-started)
    required: false
    type: string
    default: features

steps:
  - name: research_feature
    description: Research the feature in the codebase
    agent: explore
    thoroughness: very thorough
    prompt: |
      Research the {{feature_name}} feature in the codebase:

      1. Find all related code files (frontend, backend, API routes)
      2. Identify feature capabilities and user flows
      3. Determine configuration options
      4. Find dashboard views and navigation paths
      5. Extract key information about the feature

      Focus on understanding what the feature does and how users interact with it.
      Document URLs that should be screenshotted.
    outputs:
      - feature_details
      - screenshot_urls
      - capabilities

  - name: capture_screenshots
    description: Capture product screenshots
    skill: capture-screenshots
    depends_on: research_feature
    inputs:
      feature: "{{feature_name}}"
      category: "{{category}}"
      urls: "{{screenshot_urls}}"
    outputs:
      - screenshot_files

  - name: upload_screenshots
    description: Upload screenshots to Pylon CDN
    skill: sync-docs
    depends_on: capture_screenshots
    inputs:
      mode: upload-screenshots
      feature: "{{feature_name}}"
    outputs:
      - cloudfront_urls

  - name: create_documentation
    description: Generate comprehensive documentation
    skill: update-product-doc
    depends_on: upload_screenshots
    inputs:
      feature: "{{feature_name}}"
      category: "{{category}}"
      cloudfront_urls: "{{cloudfront_urls}}"
      feature_details: "{{feature_details}}"
      capabilities: "{{capabilities}}"
    outputs:
      - documentation_file

  - name: sync_to_pylon
    description: Sync documentation to Pylon KB
    skill: sync-docs
    depends_on: create_documentation
    inputs:
      mode: sync-documentation
      feature: "{{feature_name}}"
      category: "{{category}}"
      file: "{{documentation_file}}"
    outputs:
      - pylon_article_url
      - pylon_internal_url

  - name: create_announcements
    description: Generate customer announcements
    skill: create-changelog
    depends_on: sync_to_pylon
    inputs:
      feature: "{{feature_name}}"
      documentation_url: "{{pylon_article_url}}"
      capabilities: "{{capabilities}}"
    outputs:
      - slack_announcement
      - email_announcement

  - name: final_summary
    description: Create comprehensive release summary
    prompt: |
      Create a final release summary with all deliverables:

      ## 🚀 Release Complete: {{feature_name}}

      ### ✅ Deliverables

      **Screenshots:**
      - Captured: {{screenshot_files | length}} screenshots
      - Uploaded to Pylon CDN: ✅
      - CloudFront URLs: {{cloudfront_urls}}

      **Documentation:**
      - File: {{documentation_file}}
      - Pylon Article: {{pylon_article_url}}
      - Internal Edit: {{pylon_internal_url}}
      - Collection: {{category}}

      **Announcements:**
      - Slack: {{slack_announcement}}
      - Email: {{email_announcement}}

      ### 📋 Summary

      {{feature_description}}

      **Key capabilities:**
      {{capabilities}}

      ### 🔗 Quick Links

      - **Documentation:** {{pylon_article_url}}
      - **Edit in Pylon:** {{pylon_internal_url}}

      ### ✅ Next Steps

      1. Review the generated announcements
      2. Schedule announcement distribution
      3. Monitor customer feedback
      4. Update documentation based on feedback

      ---

      *🤖 Generated with max-doc-AI*

error_handling:
  strategy: continue
  on_error: |
    Document the failure and continue with remaining steps.
    Provide manual completion instructions in the final summary.

configuration:
  timeout: 1800  # 30 minutes
  auto_commit: false
  parallel_execution: false  # Must run sequentially

notes: |
  This workflow must run completely from start to finish without stopping.
  Do NOT ask the user questions unless absolutely critical.
  Make reasonable inferences from codebase research.

  Critical order: Screenshots → Upload → Documentation → Sync → Announcements

  Configuration required in config.yaml:
  - product.name, product.url
  - pylon.api_key, pylon.kb_id, pylon.collections
  - documentation.base_path, documentation.categories
  - announcements.output_dir, announcements.channels
